# Add-on Configuration
name: "SAJ Portal Scraper"
version: "1.0.24"
slug: saj_portal_scraper
description: "Fetches data from SAJ Portal using web scraping and publishes via MQTT."
arch:
  - aarch64
  - amd64
  - armv7
environment:
  SUPERVISOR_TOKEN: "{{ SUPERVISOR_TOKEN }}"
  TZ: "{{ TZ }}"
  SUPERVISOR_VERSION: "{{ SUPERVISOR_VERSION }}"
  SUPERVISOR_ARCH: "{{ SUPERVISOR_ARCH }}"
  SUPERVISOR_MACHINE: "{{ SUPERVISOR_MACHINE }}"
  SUPERVISOR_HOSTNAME: "{{ SUPERVISOR_HOSTNAME }}"
icon: icon.png
logo: logo.png
ports:
  5678/tcp: 5678 # Mapeia a porta 5678 TCP do container para a porta 5678 do host
  #1883/tcp: 1883 # Mapeia a porta MQTT padrão
ports_description: # Opcional, mas bom para documentar
  5678/tcp: Python Debugger (debugpy)
  #1883/tcp: MQTT broker (core-mosquitto)
boot: auto
homeassistant_api: true
hassio_api: true
host_network: true
# Add other supported architectures
init: false # Add-on runs as a service
options: # User-configurable options
  log_level: "info"
  timezone: "Etc/UTC"
  base_saj_url: "https://iop.saj-electric.com" # Novo campo para seleção do portal SAJ
  saj_username: ""
  saj_password: ""
  # Keep microinverters as a string for simplicity in config UI
  microinverters: "YOUR_SN1:Alias1,YOUR_SN2:Alias2"
  inactivity_enabled: true
  inactivity_start_time: "20:00"
  inactivity_end_time: "05:30"
  update_interval_seconds: 240
  data_inactivity_threshold_seconds: 1800 # Default 30 minutes (valor padrão)
  extended_update_interval_seconds: 3600 # Default 1 hour (valor padrão)
  # MQTT Configuration (Optional - can often rely on Supervisor-provided)
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  debug_mode: "false"
schema: # Defines the UI for the options
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  timezone: str
  base_saj_url: list(https://iop.saj-electric.com|https://eop.saj-electric.com|https://op.saj-electric.cn)
  saj_username: str
  saj_password: password
  microinverters: str
  inactivity_enabled: bool
  inactivity_start_time: str
  inactivity_end_time: str
  update_interval_seconds: int
  data_inactivity_threshold_seconds: int
  extended_update_interval_seconds: int
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
  debug_mode: list(false|true)
services:
  - mqtt:need # Request access to the MQTT service managed by Supervisor
map:
  - data:rw # Map /data directory for persistent state (peak power)
  - share:rw # ou :rw para leitura e escrita
  - all_addon_config:rw # Map all add-on config directories
  #- addons:rw # Map all add-ons config directories
